"""luxmodbus — HA-free framing, register map, and discovery for LuxPower inverters."""

from luxmodbus.discovery import (
    DEFAULT_HISTORY_LIMIT,
    DiscoveryStore,
    UnknownRegister,
)
from luxmodbus.protocol import (
    CrcError,
    DataFrame,
    DeviceFunction,
    Frame,
    PrefixError,
    ProtocolError,
    TcpFunction,
    TruncatedFrameError,
    crc16,
    extract_frames,
)
from luxmodbus.registers import (
    FLAG_REGISTERS,
    HOLD_REGISTERS,
    INPUT_REGISTERS,
    SELECT_REGISTERS,
    TIME_REGISTERS,
    ByteSelect,
    FlagDef,
    FlagRegister,
    Measurement,
    RegisterBank,
    RegisterDef,
    SelectRegister,
    TimeRegister,
    ValueType,
    decode_flags,
    decode_holds,
    decode_inputs,
    decode_select,
    decode_time,
    decode_value,
    encode_time,
    find_hold,
    find_input,
    mapped_hold_addresses,
    mapped_input_addresses,
    set_flag,
    set_select,
)
from luxmodbus.transport import (
    ClientTransport,
    ServerTransport,
    Transport,
    TransportConnectError,
    TransportError,
    TransportNotConnectedError,
)

__version__ = "0.0.1"

__all__ = [
    "DEFAULT_HISTORY_LIMIT",
    "FLAG_REGISTERS",
    "HOLD_REGISTERS",
    "INPUT_REGISTERS",
    "ByteSelect",
    "ClientTransport",
    "CrcError",
    "DataFrame",
    "DeviceFunction",
    "DiscoveryStore",
    "FlagDef",
    "FlagRegister",
    "Frame",
    "Measurement",
    "PrefixError",
    "ProtocolError",
    "RegisterBank",
    "RegisterDef",
    "SELECT_REGISTERS",
    "TIME_REGISTERS",
    "SelectRegister",
    "ServerTransport",
    "TcpFunction",
    "TimeRegister",
    "Transport",
    "TransportConnectError",
    "TransportError",
    "TransportNotConnectedError",
    "TruncatedFrameError",
    "UnknownRegister",
    "ValueType",
    "crc16",
    "decode_flags",
    "decode_holds",
    "decode_inputs",
    "decode_select",
    "decode_time",
    "decode_value",
    "encode_time",
    "extract_frames",
    "find_hold",
    "find_input",
    "mapped_hold_addresses",
    "mapped_input_addresses",
    "set_flag",
    "set_select",
]
